controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0

diff_drive_controller:
  ros__parameters:
    right_wheel_names: ["wheel_right_joint"]
    left_wheel_names:  ["wheel_left_joint"]

    wheel_separation: 0.076
    wheel_radius: 0.03

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true
